<?php
// Database encryption key management.
// The key lives in includes/db-key.php (a PHP file, so browsers can never
// download it — requesting it executes the script and outputs nothing).
// A SHA-256 fingerprint is stored in the settings table so setup/check can
// detect if the key file was replaced or lost.

function dbKeyFile(): string {
    return __DIR__ . '/db-key.php';
}

function dbKeyExists(): bool {
    return is_file(dbKeyFile());
}

function dbKey(): string {
    if (!dbKeyExists()) return '';
    $key = @include dbKeyFile();
    return is_string($key) ? $key : '';
}

function saveDbKey(string $key): void {
    $escaped = str_replace(['\\', "'"], ['\\\\', "\\'"], $key);
    $content = "<?php\n// Auto-generated by admin/setup.php. Do not commit this file.\nreturn '" . $escaped . "';\n";
    if (@file_put_contents(dbKeyFile(), $content, LOCK_EX) === false) {
        @file_put_contents(dbKeyFile(), $content);
    }
    @chmod(dbKeyFile(), 0600);
}

function dbKeyVerifier(string $key): string {
    return hash('sha256', $key);
}
